### ISSUE TITLE
Jahresthemen

### ISSUE THREAD

**Issue by ncqgm** [kogakure/book-kogakure#1]
Wäre das ein Kapitel wert ?

Etwas Material gäbe es hier:

   http://fudomyodojo.com/index_htm_files/Brief%20Training%20History%20of%20the%20Bujinkan.pdf

Karsten

**Comment by kogakure** [comment]
@ncqgm Ich weiß wenig über dieses Thema und mir fehlt gerade die Zeit. Möchtest du etwas darüber schreiben?
