### ISSUE TITLE
Anerkennungen

### ISSUE THREAD

**Issue by ncqgm** [kogakure/book-kogakure#2]
Wäre eine Liste der Auszeichnungen und Anerkennungen, die
im Laufe der Zeit im Bujinkan "entwickelt" wurden, eine Aufnahmen wert ?

Also Goldmedaille, Shihan, Dai Shihan, Yushu Shihan und die weiteren
"Rang"bezeichnungen, Urkunden und Ehrungen ...

(Ich meine nicht, wer was wann bekommen hat.)

Karsten

**Comment by kogakure** [comment]
@ncqgm Ich weiß fast nichts über dieses Thema. Hast du Fotos oder weißt du wo Fotos der einzelnen Auszeichnungen aufzutreiben sind? Möchtest du etwas darüber schreiben?
